language: android
jdk: oraclejdk8
notifications:
  email:
    - external-ci-notifications+android-card-form@getbraintree.com
sudo: true
android:
  components:
    - tools
    - platform-tools
    - android-28
before_install:
  - yes | sdkmanager "platforms;android-28"
script: ./gradlew --stacktrace clean lint testRelease
after_success: ./deploy_snapshot.sh
